DROP TABLE IF EXISTS SoldItem;

DROP TABLE IF EXISTS Date;

DROP TABLE IF EXISTS Receipt;

DROP TABLE IF EXISTS ProductCategory;

DROP TABLE IF EXISTS Product;

DROP TABLE IF EXISTS Customer;

DROP TABLE IF EXISTS Category;

DROP TABLE IF EXISTS StoreInfo;
