CREATE TABLE IF NOT EXISTS FiscalWeek (
    ROWguid UUID DEFAULT gen_random_uuid(),
    AddedDate TIMESTAMP DEFAULT now(),

    WeekID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    BeginDate TIMESTAMP NOT NULL,
    EndDate TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS WeeklyStoreReport (
    ROWguid UUID DEFAULT gen_random_uuid(),
    AddedDate TIMESTAMP DEFAULT now(),

    ReportID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    WeekID INTEGER NOT NULL,
    StoreName VARCHAR(50) NOT NULL,
    Revenue INTEGER NOT NULL,
    ListedPriceSum INTEGER NOT NULL,

    FOREIGN KEY (WeekID) REFERENCES FiscalWeek(WeekID)
);
